import { Injectable, Logger } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { PredictionService } from '../prediction/prediction.service';
import type { ModelInfo } from '../history/history.service';
import { HistoryService } from '../history/history.service';

@Injectable()
export class ReportsService {
  private readonly logger = new Logger(ReportsService.name);

  constructor(
    private readonly prediction: PredictionService,
    private readonly history: HistoryService,
  ) {}

  async generateReport(): Promise<Buffer> {
    // Gather all data first
    const forecast = await this.prediction.predict();
    const priceHistory = this.history.getPriceHistory();
    const elevationHistory = this.history.getElevationHistory();

    // Most recent elevation prices
    const latestElevation = Array.isArray(elevationHistory)
      ? elevationHistory[elevationHistory.length - 1]
      : null;

    // Last 6 months of national price for the trend section
    const recentTrend = Array.isArray(priceHistory)
      ? priceHistory.slice(-6)
      : [];

    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const chunks: Buffer[] = [];
        doc.on('data', (c) => chunks.push(c));
        doc.on('end', () => resolve(Buffer.concat(chunks)));

        // ── Header ──
        doc.fontSize(20).fillColor('#2D6A2D').text('SmartTeaAI', { align: 'left' });
        doc.fontSize(12).fillColor('#555')
           .text('Market Intelligence Report — Sri Lankan Tea Auction', { align: 'left' });
        doc.moveDown(0.3);
        doc.fontSize(9).fillColor('#888')
           .text(`Generated: ${new Date().toLocaleString()}`, { align: 'left' });
        doc.moveTo(50, doc.y + 8).lineTo(545, doc.y + 8).strokeColor('#ddd').stroke();
        doc.moveDown(1.5);

        // ── Section 1: Price Forecast ──
        doc.fontSize(14).fillColor('#2D6A2D').text('1. Price Forecast');
        doc.moveDown(0.5);
        doc.fontSize(11).fillColor('#000');
        doc.text(`Forecast for ${forecast.predicted_month}: Rs ${forecast.predicted_price_rs.toFixed(2)}`);
        doc.text(`Likely range: Rs ${forecast.price_range_low.toFixed(2)} - Rs ${forecast.price_range_high.toFixed(2)}`);
        doc.text(`Change from last month (${forecast.last_known_month}, Rs ${forecast.last_known_price_rs.toFixed(2)}): `
               + `${forecast.change_rs >= 0 ? '+' : ''}${forecast.change_rs.toFixed(2)} (${forecast.change_pct.toFixed(2)}%)`);
        doc.text(`Model used: ${forecast.model} (MAPE ${forecast.mape_pct}%)`);
        doc.moveDown(1);

        // ── Section 2: Risk Analysis ──
        doc.fontSize(14).fillColor('#2D6A2D').text('2. Risk Analysis');
        doc.moveDown(0.5);
        doc.fontSize(11).fillColor('#000');
        const riskColor = forecast.risk_level === 'High' ? '#C0392B'
                        : forecast.risk_level === 'Medium' ? '#C49A00' : '#2D6A2D';
        doc.text('Risk level: ', { continued: true })
           .fillColor(riskColor).text(forecast.risk_level).fillColor('#000');
        doc.text(`Range basis: ${forecast.range_basis}`);
        doc.moveDown(1);

        // ── Section 3: Recommendation ──
        doc.fontSize(14).fillColor('#2D6A2D').text('3. Recommendation');
        doc.moveDown(0.5);
        doc.fontSize(11).fillColor('#000');
        doc.text(`Signal: ${forecast.recommendation.signal}`, { continued: false });
        doc.text(forecast.recommendation.justification);
        doc.moveDown(1);

        // ── Section 4: Elevation Comparison ──
        doc.fontSize(14).fillColor('#2D6A2D').text('4. Elevation Comparison');
        doc.moveDown(0.5);
        doc.fontSize(11).fillColor('#000');
        if (latestElevation) {
          doc.text(`Latest prices (${latestElevation.month}):`);
          doc.text(`  High-Grown:   Rs ${latestElevation.price_high.toFixed(2)}`);
          doc.text(`  Medium-Grown: Rs ${latestElevation.price_medium.toFixed(2)}`);
          doc.text(`  Low-Grown:    Rs ${latestElevation.price_low.toFixed(2)}`);
        } else {
          doc.text('Elevation data not available.');
        }
        doc.moveDown(1);

        // ── Recent trend (supports Section 1) ──
        if (recentTrend.length > 0) {
          doc.fontSize(12).fillColor('#2D6A2D').text('Recent National Average Price Trend');
          doc.moveDown(0.3);
          doc.fontSize(10).fillColor('#000');
          recentTrend.forEach((p) => {
            doc.text(`  ${p.month}:  Rs ${p.price.toFixed(2)}`);
          });
        }

        // ── Footer ──
        doc.moveDown(2);
        doc.fontSize(8).fillColor('#999')
           .text('This report is generated by an AI forecasting system and is intended as decision support, '
               + 'not financial advice. Forecasts carry uncertainty and should be considered alongside other information.',
               { align: 'center' });

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }

  generateHistoryCsv(): string {
    const rows = this.history.getPriceHistory();
    const header = 'month,price_lkr,split';
    const lines = rows.map(r => `${r.month},${r.price},${r.split}`);
    return [header, ...lines].join('\n');
  }

  async generateModelReport(): Promise<Buffer> {
    const raw = this.history.getModelInfo();
    const info = 'best_model' in raw ? (raw as ModelInfo) : null;

    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const chunks: Buffer[] = [];
        doc.on('data', (c) => chunks.push(c));
        doc.on('end', () => resolve(Buffer.concat(chunks)));

        doc.fontSize(20).fillColor('#2D6A2D').text('SmartTeaAI');
        doc.fontSize(12).fillColor('#555').text('Model Performance Report');
        doc.moveDown(0.3);
        doc.fontSize(9).fillColor('#888').text(`Generated: ${new Date().toLocaleString()}`);
        doc.moveTo(50, doc.y + 8).lineTo(545, doc.y + 8).strokeColor('#ddd').stroke();
        doc.moveDown(1.5);

        if (!info) {
          doc.fontSize(11).fillColor('#000').text('Model information is not available yet. Run the training pipeline first.');
        } else {
          doc.fontSize(14).fillColor('#2D6A2D').text('Best Model');
          doc.moveDown(0.5);
          doc.fontSize(11).fillColor('#000');
          doc.text(`Model: ${info.best_model}`);
          doc.text(`MAPE: ${info.mape_pct.toFixed(2)}%`);
          doc.text(`RMSE: ${info.rmse.toFixed(2)}`);
          doc.text(`R²: ${info.r2.toFixed(4)}`);
          doc.text(`Trained on: ${info.trained_on}`);
          doc.text(`Test period: ${info.test_period}`);
          doc.moveDown(1);

          if (info.all_results?.length) {
            doc.fontSize(14).fillColor('#2D6A2D').text('All Model Comparison');
            doc.moveDown(0.5);
            doc.fontSize(10).fillColor('#000');
            info.all_results.forEach(r => {
              doc.text(`${r.Model.padEnd(20)} MAPE: ${r['MAPE(%)'].toFixed(2)}%  RMSE: ${r.RMSE.toFixed(2)}  R²: ${r.R2.toFixed(4)}`);
            });
          }
        }

        doc.moveDown(2);
        doc.fontSize(8).fillColor('#999')
           .text('This report is generated by SmartTeaAI and is intended as decision support.', { align: 'center' });

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }
}